# Generated by Django 5.0.4 on 2024-05-10 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Identifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=12, unique=True)),
                ('current_status', models.CharField(max_length=100, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=100, null=True)),
                ('json_location', models.CharField(max_length=300, null=True)),
            ],
            options={
                'verbose_name': 'Identifier',
                'verbose_name_plural': 'Identifiers',
                'db_table': 'identifiers',
            },
        ),
        migrations.CreateModel(
            name='IdentifierTempTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp_name', models.CharField(max_length=100)),
                ('file_location', models.CharField(max_length=300)),
                ('add_status', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Identifier Temp Table',
                'verbose_name_plural': 'Identifier Temp Tables',
                'db_table': 'identifiers_temp_table',
            },
        ),
    ]
