# Generated by Django 5.0.4 on 2024-05-10 02:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('videos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoTimestamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_stamp', models.CharField(default='', max_length=100)),
                ('serial', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='watch_location', to='videos.video')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='watch_location', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Video Timestamp',
                'verbose_name_plural': 'Video Timestamps',
                'db_table': 'video_timestamp',
            },
        ),
    ]
